stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building application"

test:
  stage: test
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying application"


